{% set version = environ.get('PYTHON_VERSION', '0.0.0.1') %}

package:
  name: qsharp
  version: "{{ version }}"

source:
  - path:    ../../
    folder:  src

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - jupyter_client<5.3.3
    - iqsharp={{ version }}

  run:
    - python
    - iqsharp={{ version }}

build:
  script: |
    powershell -NoProfile src/conda-recipes/qsharp/build.ps1 # [win]
    pwsh src/conda-recipes/qsharp/build.ps1 # [not win]

test:
  requires:
    - python
    - iqsharp={{ version }}
    - pytest

  source_files:
    - src/conda-recipes/qsharp/test.ps1
    - src/conda-recipes/qsharp/tests.py

  commands:
    - powershell -NoProfile src/conda-recipes/qsharp/test.ps1 # [win]
    - pwsh src/conda-recipes/qsharp/test.ps1 # [not win]

about:
  home: https://docs.microsoft.com/quantum
  license: MIT
  summary: Python client for Q#, a domain-specific quantum programming language
  dev_url: https://github.com/microsoft/iqsharp
