{% set version = environ.get('PYTHON_VERSION', '0.0.0.1') %}

package:
  name: qsharp
  version: "{{ version }}"

source:
  - path:    ../../
    folder:  src

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - jupyter_client<5.3.3
    - iqsharp={{ version }}

  run:
    - python
    - jupyter_client<5.3.3
    - iqsharp

build:
  script: |
    powershell -NoProfile src/conda-recipes/qsharp/build.ps1 # [win]
    pwsh src/conda-recipes/qsharp/build.ps1 # [not win]

# test:
#   requires:
#     - python
#     - jupyter_client
#     - iqsharp

#   source_files:
#     - iqsharp/conda-recipes/iqsharp/test.ps1
#     - iqsharp/conda-recipes/iqsharp/test.py

#   commands:
#     - powershell -NoProfile iqsharp/conda-recipes/iqsharp/test.ps1 # [win]
#     - pwsh iqsharp/conda-recipes/iqsharp/test.ps1 # [not win]
#     - pip install jupyter_kernel_test
#     - python iqsharp/conda-recipes/iqsharp/test.py

about:
  home: https://docs.microsoft.com/quantum
  license: MIT
  summary: Python client for Q#, a domain-specific quantum programming language
  dev_url: https://github.com/microsoft/iqsharp
