{% set version = environ.get('PYTHON_VERSION', '0.0.0.1') %}

package:
  name: iqsharp
  version: "{{ version }}"

source:
  - path:    ../../
    folder:  src

build:
  binary_relocation: False
  detect_binary_files_with_prefix: False
  has_prefix_files:
    - share/jupyter/kernels/iqsharp/kernel.json
  script: |
    powershell -NoProfile src/conda-recipes/iqsharp/build.ps1 # [win]
    pwsh src/conda-recipes/iqsharp/build.ps1 # [not win]

requirements:
  build:
    - python
    - setuptools
    - jupyter

  run:
    - python
    - jupyter_client
    - backports.weakref  # for https://github.com/microsoft/iqsharp/issues/39

test:
  requires:
    - notebook=6.0.1
    - python>=3.6
    - jupyter_client<5.3.3
    - pip

  source_files:
    - src/conda-recipes/iqsharp/test.ps1
    - src/conda-recipes/iqsharp/test.py

  commands:
    - pip install jupyter_kernel_test
    - powershell -NoProfile src/conda-recipes/iqsharp/test.ps1 # [win]
    - pwsh src/conda-recipes/iqsharp/test.ps1 # [not win]

about:
  home: https://docs.microsoft.com/quantum
  license: MIT
  summary: Microsoft's IQ# Server.
  dev_url: https://github.com/microsoft/iqsharp
