{% set version = environ.get('PYTHON_VERSION', '0.0.0.1') %}

package:
  name: iqsharp
  version: "{{ version }}"

source:
  - path:    ../../
    folder:  src

build:
  binary_relocation: False
  detect_binary_files_with_prefix: False
  has_prefix_files:
    - share/jupyter/kernels/iqsharp/kernel.json
  script: |
    powershell -NoProfile src/conda-recipes/iqsharp/build.ps1 # [win]
    pwsh src/conda-recipes/iqsharp/build.ps1 # [not win]

requirements:
  build:
    - python
    - setuptools
    - jupyter

  run:
    - python
    - jupyter_client
    - pyzmq

test:
  requires:
    - notebook
    - python>=3.6
    # See microsoft/iqsharp#515, jupyter/jupyter_kernel_test#56.
    - jupyter_client==6.1.12
    - pyzmq
    - pip

  source_files:
    - src/conda-recipes/iqsharp/test.ps1
    - src/conda-recipes/iqsharp/test.py

  commands:
    - pip install jupyter_kernel_test
    - powershell -NoProfile src/conda-recipes/iqsharp/test.ps1 # [win]
    - pwsh src/conda-recipes/iqsharp/test.ps1 # [not win]

about:
  home: https://docs.microsoft.com/azure/quantum
  license: MIT
  summary: Microsoft's IQ# kernel providing Q# support for the Jupyter platform.
  description: |
    For details on how to get started with Jupyter and Q#, please see the guide at https://docs.microsoft.com/azure/quantum/install-jupyter-qkd.
    You can also try our Quantum Computing Fundamentals learning path (https://aka.ms/learnqc) to get familiar with the basic concepts
    of quantum computing, build quantum programs, and identify the kind of problems that can be solved.
  dev_url: https://github.com/microsoft/iqsharp
  doc_url: https://docs.microsoft.com/azure/quantum/install-jupyter-qkd
