// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Microsoft.Quantum.IQSharp.Common
{
    /// <summary>
    /// The status after executing the requested operation.
    /// </summary>
    public enum Status
    {
        Success,
        Error
    }

    /// <summary>
    ///  A data structure representing the response from one of the Controllers.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class Response<T>
    {
        public Response() { }

        public Response(Status status, IEnumerable<string> messages, T result = default(T))
        {
            this.Status = status;
            this.Messages = messages.ToArray();
            this.Result = result;
        }

        /// <summary>
        /// Whether the request ended in success or error. 
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public Status Status { get; set; }

        /// <summary>
        /// List of messages generated by the call. For example, it can return 
        /// the list of warnings from a successful compilation, or the list of Messages
        /// from a Q# simulation.
        /// </summary>
        public string[] Messages { get; set; }

        /// <summary>
        /// The actual result from the operation. From simulation this is the result of
        /// the operation being simulated. For compilation, the list of operations found in the snippet.
        /// </summary>
        public T Result { get; set; }
    }
}
