name: Push Docker test images

on:
  push:
    branches:
    - main
    paths:
    - 'images/test-environments/**/Dockerfile'
  workflow_dispatch:

jobs:
  windows:
    name: "Build windows image"
    uses: ./.github/workflows/docker-build.yml
    with:
      os: "windows-latest"
      path: "images/test-environments/windows"
      repoName: "windows-selfcontained"
      tagSuffix: "windows"

  linux:
    name: "Build linux image"
    uses: ./.github/workflows/docker-build.yml
    with:
      os: "ubuntu-latest"
      path: "images/test-environments/linux"
      repoName: "linux-selfcontained"
      tagSuffix: "linux"
